server.port: 8084

management.endpoints.web.exposure.include: "*"

ribbon:
  serverListRefreshInterval: 1000
  ConnectTimeout: 6000
  ReadTimeout: 3000

hystrix.command.default.execution.isolation:
  thread.timeoutInMilliseconds: 10000
  strategy: THREAD

feign.hystrix.enabled: true


spring:
  application.name: frontend
  cloud.config:
    discovery:
      enabled: true

    fail-fast: true
    retry:
      initialInterval: 2000
      maxAttempts: 30
  mvc.servlet.load-on-startup: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1

vaadin.urlMapping: /ui/*
server.servlet.context-path: /
